name: Sync Charts
on:
  push:
    branches:
      - main
      - rc

permissions:
  contents: write
  packages: write
  repository-projects: write

jobs:
  chart:
    uses: codedesignplus/workflows/.github/workflows/helm-chart.yaml@main
    with:
      project-name: CodeDesignPlus.Net.Microservice.Tenants
      microservice-name: ms-tenants
      enable-rest: true
      enable-grpc: true
      enable-worker: true
    secrets: inherit